### ISSUE TITLE
ทุนวิจัย/ฝึกงานระยะสั้นเพื่อสังคม

### ISSUE THREAD

**Issue by c4n** [codeforthailand/study-abroad#1]
Data Science For Social Good 
url: https://dssg.uchicago.edu/
วันปิดรับสมัครครั้งก่อน: Jan 31st, 2019
สถานที่: USA/Europe
สาขาที่ครอบคลุม: data science, machine learning, computational social science, public policy
ระยะเวลา: 3 เดือน

Mozilla Fellowships
url: https://foundation.mozilla.org/en/fellowships/
วันปิดรับสมัครครั้งก่อน:  April 8, 2019 
สถานที่: multiple locations
สาขาที่ครอบคลุม: open source engineering, open internet, open science, public policy
ระยะเวลา: 10 เดือน

Voting Rights Data Institute 
url: http://gerrydata.org/
วันปิดรับสมัครครั้งก่อน:  Feb 1, 2019 
สถานที่: Boston, USA
สาขาที่ครอบคลุม: mathematics, computer science
ระยะเวลา:  6 สัปดาห์

United Nations Global Pulse
url: https://www.unglobalpulse.org/participate/vacancies
วันปิดรับสมัครครั้งก่อน:  Ongoing
สถานที่: Kampala, Uganda/ Jakarta, Indonesia
สาขาที่ครอบคลุม: computer science, political science, management, communication
ระยะเวลา: -

**Comment by heytitle** [comment]
Added : https://codeforthailand.github.io/study-abroad/?type=internship
