### ISSUE TITLE
6 SFI Centres for Research Training (Ireland, PhD)

### ISSUE THREAD

**Issue by bact** [codeforthailand/study-abroad#4]
https://docs.google.com/spreadsheets/d/11CZv4kv7uMkX2QQmh0ZfUBtAv7WSWgfC3Uwo9lDtyIs/edit?usp=sharing 

บางอันยังไม่รู้เวลาเปิดหรือปิดรับสมัคร

**Comment by heytitle** [comment]
Sry, I've just seen this issue. I'll update the database accordingly.
